### ISSUE TITLE
Hidden Ability Patches

### ISSUE THREAD

**Issue by ShadowzLmao2** [rh-hideout/pokeemerald-expansion#4770] opened 2024-06-12 00:52 UTC
### Description

I get traded a pokemon with its hidden ability and you use the patch and it become the hidden ability (Same ability) and i need to use another patch to make it the normal ability. Very odd

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

not 100% sure. updated it like 3 days ago

### Discord contact info

SShadowzLmao#3643

**Comment by pkmnsnfrn** [comment] 2024-06-12 18:48
To be clear, when you used an Ability Patch on a Pokémon with its Hidden Ability, what happened?

1) Ability Patch failed, was not chosen (Gen 8 behavior)
2) Ability Patch failed, item was consumed (bug)
3) Ability Patch failed, item was consumed, then Ability Patch changes ability to 1 (bug, and implied in the report)
4) Ability Patch changes to Ability 0 (Gen 9 behavior)

**Comment by ShadowzLmao2** [comment] 2024-06-20 02:18
> To be clear, when you used an Ability Patch on a Pokémon with its Hidden Ability, what happened?
> 
> 1. Ability Patch failed, was not chosen (Gen 8 behavior)
> 2. Ability Patch failed, item was consumed (bug)
> 3. Ability Patch failed, item was consumed, then Ability Patch changes ability to 1 (bug, and implied in the report)
> 4. Ability Patch changes to Ability 0 (Gen 9 behavior)

What happened was it used the patch and the ability was still the hidden ability. A second patch made the ability its normal ability

**Comment by pkmnsnfrn** [comment] 2024-06-20 05:24
Fascinating, so number 3. Good to know.

**Comment by Bassoonian** [comment] 2024-06-20 10:34
Can you specify which Pokémon and which abilities?

**Comment by ShadowzLmao2** [comment] 2024-06-20 16:17
It was an in game trade with an npc at winona's town for Tyranitar. Its normal ability was Unnerve and it's hidden ability was Dark Aura. It was not between two roms cus idk how to do that

**Comment by Bassoonian** [comment] 2024-06-20 16:25
Since you seem to have changed the species properties, can you post the following data:
- `SPECIES_TYRANITAR` from `src/data/pokemon/species_info/gen_2_families.h`
- The in-game trade information for this Tyranitar from `sIngameTrades`
- Ideally the species data + information of the Pokémon you traded in exchange for Tyranitar

Without the exact details, we'd just be guessing trying to reproduce it and find the cause. Alternatively, you could try to replicate this on a (mostly) clean branch of expansion and let us know how to reproduce it.

**Comment by ShadowzLmao2** [comment] 2024-06-20 16:33
#if P_MEGA_EVOLUTIONS
    [SPECIES_TYRANITAR_MEGA] =
    {
        .baseHP        = 100,
        .baseAttack    = 164,
        .baseDefense   = 150,
        .baseSpeed     = 81,
        .baseSpAttack  = 95,
        .baseSpDefense = 120,
        .types = MON_TYPES(TYPE_ROCK, TYPE_DARK),
        .catchRate = 45,
        //expyield = (P_UPDATED_EXP_YIELDS >= GEN_8) ? 350 : 315,
        //evyield_Attack = 3,
        .genderRatio = PERCENT_FEMALE(50),
        .eggCycles = 40,
        .friendship = 35,
        .growthRate = GROWTH_SLOW,
        .eggGroups = MON_EGG_GROUPS(EGG_GROUP_MONSTER),
        .abilities = { ABILITY_DARK_AURA, ABILITY_DARK_AURA, ABILITY_DARK_AURA },
        .bodyColor = BODY_COLOR_GREEN,
        .speciesName = _("Tyranitar"),
        .cryId = CRY_TYRANITAR_MEGA,
        .natDexNum = NATIONAL_DEX_TYRANITAR,
        .categoryName = _("Armor"),
        .height = 25,
        .weight = 2550,
        .description = COMPOUND_STRING(
            "Due to the colossal power poured into it,\n"
            "this Pokémon's back split right open. Its\n"
            "destructive instincts are the only thing\n"
            "keeping it moving."),
        .pokemonScale = 256,
        .pokemonOffset = 0,
        .trainerScale = 345,
        .trainerOffset = 7,
        .frontPic = gMonFrontPic_TyranitarMega,
        .frontPicSize = MON_COORDS_SIZE(64, 64),
        .frontPicYOffset = 0,
        .frontAnimFrames = sAnims_TyranitarMega,
        //.frontAnimId = ANIM_V_SQUISH_AND_BOUNCE,
        .backPic = gMonBackPic_TyranitarMega,
        .backPicSize = MON_COORDS_SIZE(64, 64),
        .backPicYOffset = 0,
        .backAnimId = BACK_ANIM_V_SHAKE_LOW,
        .palette = gMonPalette_TyranitarMega,
        .shinyPalette = gMonShinyPalette_TyranitarMega,
        .iconSprite = gMonIcon_TyranitarMega,
        .iconPalIndex = 1,
        FOOTPRINT(Tyranitar)
        .isMegaEvolution = TRUE,
        .levelUpLearnset = sTyranitarLevelUpLearnset,
        .teachableLearnset = sTyranitarTeachableLearnset,
        .formSpeciesIdTable = sTyranitarFormSpeciesIdTable,
        .formChangeTable = sTyranitarFormChangeTable,
    },


    [INGAME_TRADE_PLUSLE] =
    {
        .nickname = _("ROCK-HARD"),
        .species = SPECIES_PUPITAR,
        .ivs = {4, 4, 4, 5, 5, 4},
        .abilityNum = 1,
        .otId = 73996,
        .conditions = {5, 5, 30, 5, 5},
        .personality = 0x6F,
        .heldItem = ITEM_NONE,
        .mailNum = 0,
        .otName = _("LMAO"),
        .otGender = MALE,
        .sheen = 10,
        .requestedSpecies = SPECIES_PSYDUCK
    },

**Comment by ShadowzLmao2** [comment] 2024-06-20 16:34
oh i see the problem. mb

**Comment by Bassoonian** [comment] 2024-06-20 16:42
I'm sorry, but you changed the species data since you first posted it. Did you find the cause of the issue? Considering you deleted a comment saying `oh i see the problem. mb`, I assume it was your bad and it's safe to close this issue?

**Comment by pkmnsnfrn** [comment] 2024-06-20 16:48
Oh, this isn't on a clean branch? We should 100% test something in a clean branch before digging deeper imho

**Closed** 2024-06-21 00:44 UTC
Labels: bug, category: battle-mechanic, status: unconfirmed
