### ISSUE TITLE
The Mega Evolution icon doesn't function properly in double battles

### ISSUE THREAD

**Issue by surskitty** [rh-hideout/pokeemerald-expansion#1404] opened 2021-02-10 23:00 UTC
![mega evolution icon](https://user-images.githubusercontent.com/1383512/107583972-b25d7580-6bc9-11eb-9689-1d855b0c08c7.png)
The opponent's mega evolved pokemon had already fainted, but the icon continues to persist.

Not tested on a clean branch, but I am close to up to date.

**Comment by BuffelSaft** [comment] 2021-07-25 09:31
Can confirm this, seems to happen consistently when an opponent's mega faints in a double battle. Doesn't seem to affect the player's side.

**Comment by AsparagusEduardo** [comment] 2021-10-02 13:00
#1607

**Comment by DizzyEggg** [comment] 2023-02-15 09:54
Couldn't reproduce on upcoming. Could anyone else try it?

**Comment by AlexOn1ine** [comment] 2023-02-15 11:47
Works fine for me.

**Comment by AsparagusEduardo** [comment] 2023-02-15 11:50
Let's close this issue for now, as it literally submitted 2 years ago. If we find that it happens again, let's try finding a way to replicate it there and then before opening a new issue.

**Closed by AsparagusEduardo** 2023-02-15 11:50 UTC
Labels: category:battle-related, status: unconfirmed
