### ISSUE TITLE
Out of bounds error on new fresh pokeemerald expansion (pret clone with rh-hidout pull)

### ISSUE THREAD

**Issue by bnthomason** [rh-hideout/pokeemerald-expansion#5067] opened 2024-07-31 01:41 UTC
### Description

```
src/clear_save_data_screen.c: In function 'SetupClearSaveDataScreen.part.0':
src/clear_save_data_screen.c:153:44: error: '__builtin_memset' offset [0, 31] is out of the bounds [0, 0] [-Werror=array-bounds]
  153 |             ((u16 *)(VRAM + 0x20))[i] = 0x1111;
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
cc1: all warnings being treated as errors
Makefile:400: recipe for target 'build/modern/src/clear_save_data_screen.o' failed
make: *** [build/modern/src/clear_save_data_screen.o] Error 1
make: *** Deleting file 'build/modern/src/clear_save_data_screen.o'
```

I have no idea why this is happening and am not a very good programmer/debugger.

Any ideas on how to fix this?

Also, I ran into a warning earlier in the make: ```/opt/devkitpro/devkitARM/bin/../libexec/gcc/arm-none-eabi/11.2.0/cc1 -quiet <flags> -o build/modern/src/agb_flash_mx.o src/agb_flash_mx.c
In function 'EraseFlashSector_MX',
    inlined from 'EraseFlashSector_MX' at src/agb_flash_mx.c:77:5:
src/agb_flash_mx.c:102:11: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  102 |     *addr = 0x30;
      |     ~~~~~~^~~~~~```

### Version

master (default, unreleased bugfixes)

### Upcoming/master Version

1.8.5

**Comment by hedara90** [comment] 2024-07-31 14:22
Did you clone the pret pokeemerald repo, then pull pokeemerald-expansion into that folder?
Did I understand the title correctly?
If so I am quite sure that that is not supposed to work. You clone pokeemerald-expansion by itself.

**Comment by tertu-m** [comment] 2024-08-02 19:19
@hedara90 that shouldn't cause this problem (unless the git pull was done in the same branch)

**Comment by Bassoonian** [comment] 2024-08-10 22:54
@bnthomason can you please elaborate? We won't be able to figure this out more until you do so. Thank you

**Comment by tertu-m** [comment] 2024-08-31 15:44
We cannot reproduce this and cannot look into this further at this point. I am closing it, please feel free to re-open if you can provide more info

**Closed by tertu-m** 2024-08-31 15:44 UTC
Labels: bug, status: needs information, status: unconfirmed

**Comment by TristanaGW** [comment] 2024-09-02 12:49
Was getting this error when trying to `make` on a fresh clone of `rh-hideout/pokeemerald-expansion`. Problem was fixed by updating devkitARM. No idea when I had last updated it, so no idea what would have changed, unfortunately.

**Comment by bnthomason** [comment] 2024-09-02 22:25
Hey, sorry, I am no longer having this issue. It had something to do with devkitARM, possibly being out of date. I switched to Modern and the problem went away, and forgot about the issue I opened. I apologize.
