### ISSUE TITLE
mapjson isn't automatically built on latest upcoming

### ISSUE THREAD

**Issue by innocenthedgehog** [rh-hideout/pokeemerald-expansion#4991] opened 2024-07-17 19:37 UTC
### Description

On the latest build of upcoming, tools/mapjson/mapjson is not getting built when running `make` in the root directory. This leads to src/debug.c throwing an error because src/data/map_group_count.h hasn't been created.

I had to go into tools/mapjson and build it manually. It worked fine after that.

### Version

upcoming (Edge)

### Upcoming/master Version

d333f9f

### Discord contact info

innocenthedgehog

**Comment by pkmnsnfrn** [comment] 2024-07-29 17:05
I'm on https://github.com/PokemonSanFran/pokeemerald-expansion/commit/18aff2db3bf310d703cd548c167f9aa447a319ca and I can't reproduce this issue.

**Comment by pkmnsnfrn** [comment] 2024-07-29 17:07
I also can't reproduce it on d333f9f06617a1e746d6c6e1f5beb6240c9a71d1.

**Comment by pkmnsnfrn** [comment] 2024-07-29 17:12
https://discord.com/channels/419213663107416084/774393519569502268/1267529963393781910

Closing this for now. Please reopen if you are able to reproduce.

**Closed by pkmnsnfrn** 2024-07-29 17:12 UTC
Labels: bug, status: needs information, status: unconfirmed
