### ISSUE TITLE
#2142 makes Move Tutors edit your level

### ISSUE THREAD

**Issue by eatthepear** [rh-hideout/pokeemerald-expansion#2275] opened 2022-08-30 13:15 UTC
Disclaimer: my game has a number of changes in both the move tutor code and the level up code, but after looking through the code, I think it is still a bug in rhh's code. Essentially, CB2_ReturnToPartyMenuWhileLearningMove contains `SetMonData(&gPlayerParty[gPartyMenu.slotId], MON_DATA_LEVEL, &sFinalLevel); // to avoid displaying incorrect level`
However, this line is reached when learning a new move tutor move, resulting in your Pokemon's level being set to whatever the last sFinalLevel was.

**Comment by gruxor** [comment] 2022-08-30 13:43
Have you pulled changes since #2233 was merged?

If so, the changes most likely conflict with your existing changes. If not, then this issue (if it truly was caused by #2142) probably isn't an issue anymore as #2233 reworked the entire system.

**Comment by eatthepear** [comment] 2022-08-30 13:49
Yep, I encountered this bug a couple hours ago when I pulled from RHH, and #2233 was already merged at the time. I just looked through that particular PR and found no mention of sFinalLevel, meaning I think the bug remains. I could be wrong, of course, but would love if someone has a vanilla save file to test it out.

**Comment by gruxor** [comment] 2022-08-30 13:55
There isn't an `sFinalLevel` anywhere in the codebase, nor does `CB2_ReturnToPartyMenuWhileLearningMove` contain a `SetMonData` call as far as I can see.

Either this is an addition from elsewhere, or it's leftover from a previous version and was since removed.

**Comment by eatthepear** [comment] 2022-08-30 13:57
Are you sure you're looking at the right file? I'm looking at this file: https://github.com/rh-hideout/pokeemerald-expansion/blob/master/src/party_menu.c

**Comment by gruxor** [comment] 2022-08-30 14:10
Whoops, looks like I was the one out of date.

Yeah, I see the code now - not sure why it was added. I'll do some poking around.

**Comment by AsparagusEduardo** [comment] 2022-09-21 19:56
#2282

**Closed by AsparagusEduardo** 2022-09-21 19:56 UTC
