### ISSUE TITLE
Innards Out hit for way too much damage

### ISSUE THREAD

**Issue by wiz1989** [rh-hideout/pokeemerald-expansion#5921] opened 2024-12-31 18:48 UTC
### Description

Pyukumuku was hit and killed by Future Sight which was originally executed by Slowking.
At this moment it had roughly 10 HP left.

However, Innards Out OHKO'd Slowking in return where from Bulbapedia it seems that it should only deal the amount of damage that the opponent suffered for being killed. So roughly the 10 HP.

Description: "When a Pokémon with this Ability is knocked out by an opponent's attack, it deals damage to that opponent equal to the amount of HP it had left before last being hit."

https://github.com/user-attachments/assets/5a7f3b26-fbb4-4c54-ba06-8975f0bff338

### Version

1.9.4

### Discord contact info

wiz1989

**Comment by hedara90** [comment] 2024-12-31 18:55
Duplicate of #4934

**Closed by hedara90** 2024-12-31 18:55 UTC
Labels: bug, status: duplicate, category: battle-mechanic, status: unconfirmed
