### ISSUE TITLE
Charcadet Sprite Off Centered in battle

### ISSUE THREAD

**Issue by RWXOLIVE** [rh-hideout/pokeemerald-expansion#4892] opened 2024-06-30 19:52 UTC
### Description

Sprite in battle is hovering 
![image_2024-06-30_205213151](https://github.com/rh-hideout/pokeemerald-expansion/assets/163889652/58fa5a41-507e-4b2d-89e7-c215835da4df)

### Version

1.8.4 (Latest release)

### Discord contact info

rwxo

**Comment by Bassoonian** [comment] 2024-07-18 19:21
Presumably already fixed in 1.8.5, can't reproduce
<img width="1348" alt="image" src="https://github.com/user-attachments/assets/9263e263-7d1f-486e-9d34-cdfeac4c231b">

**Closed by Bassoonian** 2024-07-18 19:21 UTC
Labels: category: sprite-issue
