### ISSUE TITLE
Intimidate tries to Lower Atk of a fainted Mon

### ISSUE THREAD

**Issue by Syreldar** [rh-hideout/pokeemerald-expansion#1570] opened 2021-07-14 00:55 UTC
Video:
https://user-images.githubusercontent.com/42327659/125543865-01ada889-4478-4d77-8960-b6e49dbf1eb4.mp4

**Comment by LOuroboros** [comment] 2021-07-14 11:43
Duplicate of #1405

**Closed** 2021-07-14 13:05 UTC
