### ISSUE TITLE
Overworld Following Pokémon break for species with IDs 1536 and higher.

### ISSUE THREAD

**Issue by SarnPoke** [rh-hideout/pokeemerald-expansion#5105] opened 2024-08-06 13:16 UTC
### Description

**Overworld following sprites do not display correctly for species with species constant IDs 1536 and higher.**

Current erroneous behavior is that following mons for species with IDs higher than or equal to **1536** will first show as default substitute doll and then switch to using the correctly defined sprite but with the substitute doll palette upon reloading the graphics without a warp taking place (exiting a battle, entering and exiting the party menu, etc.) Entering a building turns the mon back into the substitute doll until the graphics are reloading once more as mentioned previously.

Additionally, the sprites do not display correctly when viewing them in the debug sprite viewer menu.

**Pokémon with ID 1535 showing expected behavior:**
![image](https://github.com/user-attachments/assets/f7a03f45-7c7d-40f9-a4ce-643acb62b4bf)
![image](https://github.com/user-attachments/assets/f148e962-8375-4ead-9871-9aa91c890a7a)

**Pokémon with ID 1536 showing erroneous behavior:**
![image](https://github.com/user-attachments/assets/48576d20-b271-4908-a136-45ac70dec387)

**Before reloading the graphics in the overworld:**
![image](https://github.com/user-attachments/assets/b06f2d32-e4a3-4b56-a380-23f50ef64883)

**After reloading the graphics in the overworld:**
![image](https://github.com/user-attachments/assets/9a4b2697-f9d5-44ba-9317-cc533eeef7ad)

**To reproduce:**
1. Add necessary entries for 14 new species in `include/constants/species.h`, `src/data/pokemon/species_info.h` and `include/constants/pokedex.h`. You can copy existing data to make it faster. (Turtwig overworld sprites and Oinkologne battle sprites copied for example.)

**Done on clean latest expansion without any further edits.**

### Version

1.9.0 (Latest release)

### Discord contact info

sarnnn

**Comment by mrgriffin** [comment] 2024-08-06 13:26
Some thoughts:
- 1536 = 1024 + 512. Those numbers are suspicious.

- `OBJ_EVENT_GFX_MON_BASE` is 512.
- `OBJ_EVENT_GFX_SPECIES_BITS` is `11`.
- So for OBJ_EVENT_GFX_SPECIES(1536) we have `1536 + 512` => `2048`?
- And then for `OW_SPECIES(OBJ_EVENT_GFX_SPECIES(1536))` we have `(2048 & (1 << 11)) - 512` => `-512`? (`2048 & (1 << 11)` => `0`)

**Comment by mrgriffin** [comment] 2024-08-06 13:30
Question for people who are more familiar with followers: is it safe to increase `OBJ_EVENT_GFX_SPECIES_BITS` to `12`? This may interfere with `OW_FORM` (it will have one fewer bit).

An alternative idea is subtracting `OBJ_EVENT_GFX_MON_BASE` before masking which should allow us to keep 11 bits, but I don't know what the consequences (if any) of that would be for the rest of the implementation.

**Comment by SarnPoke** [comment] 2024-08-06 14:29
Can confirm that setting `OBJ_EVENT_GFX_SPECIES_BITS` to `12` solves this issue seemingly. If somebody with a decent to good amount of knowledge could jump in and confirm whether this is a viable solution or not, please do.

**Comment by hedara90** [comment] 2024-08-06 20:58
I cannot reproduce the problem, precisely.
Instead of the reported behavior I see a full game freeze with `[WARN] GBA:	Illegal opcode: e0e0f0f0` as the output.
Also it's only 13 new species that need to be added... Don't be like me and add 14 species then test with giving the last and 2nd last species.

**Comment by SarnPoke** [comment] 2024-08-06 21:23
@hedara90 
Here's all the changes I made to make the problem appear:

In `include/constants/species.h`:
![image](https://github.com/user-attachments/assets/c77d39b7-1114-427a-9bc4-cac4655aeb68)

In `src/data/species_info.h`:
![image](https://github.com/user-attachments/assets/db526f6d-2418-4ac6-aedc-3471731da89e)
(Basically just this 14 times with different names)

In `include/constants/pokedex.h`:
![image](https://github.com/user-attachments/assets/1e0747e9-1d74-40b5-90b2-01035aa54015)

And that's pretty much the extent of it. Did you do basically the same thing and end up with a different result?

**Comment by hedara90** [comment] 2024-08-06 21:26
Yea, I did the same. Only difference is that I used Bulbasaur as the base for the copy.

**Comment by SarnPoke** [comment] 2024-08-06 21:38
@hedara90 
Is the crash consistent? Can you confirm if setting `OBJ_EVENT_GFX_SPECIES_BITS` in `include/constants/event_objects.h` to `12` solves the issue for you? It solved it on my end. It could be that I just never pushed it hard enough to crash like for you.

**Comment by hedara90** [comment] 2024-08-06 21:50
Yes, it's consistent. It happens the moment the pokeball opens when taking a step to the side after starting the game.

**Comment by hedara90** [comment] 2024-08-08 06:58
I've tested the fix quite extensively. Every overworld sprite is working with both normal and shiny palette (if they exist), checked in the sprite viewer. In the overworld a subset of pokemon were tested and they worked there too. I looked at the code and tried to see if it would break something, but couldn't see anything immediately.
It seems that the `OBJ_EVENT_GFX_SPECIES_BITS` increase works.
Do you want to PR it @mrgriffin ?

**Comment by hedara90** [comment] 2024-08-15 18:20
Fixed by #5179

**Closed by hedara90** 2024-08-15 18:20 UTC
Labels: bug, status: confirmed, category:  overworld
