### ISSUE TITLE
Deoxys icon is glitched

### ISSUE THREAD

**Issue by veterandrake** [rh-hideout/pokeemerald-expansion#1309] opened 2020-12-21 14:25 UTC
deoxy index 386 icon is not correct.
![deoxy](https://user-images.githubusercontent.com/75160712/102787004-6ad71c00-43c6-11eb-9eb1-4e6a1be2a6b6.png)

**Comment by ExpoSeed** [comment] 2020-12-22 06:45
duplicate of #534

**Closed by ExpoSeed** 2020-12-22 06:45 UTC
Labels: status: duplicate
