### ISSUE TITLE
Sending in Pokemon animation glitch with switching and Zoroark.

### ISSUE THREAD

**Issue by MythicalBlueFlare** [rh-hideout/pokeemerald-expansion#2378] opened 2022-10-07 02:22 UTC
While fighting a trainer that had a Zoroark, the AI switched out its current mon into the Zoroark, which was disguised as a Grimmsnarl, and when the game went to play the Grimmsnarl's animation, it instead played Krookodile's with a palette swap. The exact situation was "Scarf Krook switches out on flying mon as it is locked into eq, swaps into Zoroark, disguises as Grimmsnarl since it is the farthest back alive mon (the actual farthest back is fainted), and the animation plays Krookodile with Grimmsnarl's palette before quickly returning to Grimmsnarl." I could grab a  clip of it if needed.

**Comment by AsparagusEduardo** [comment] 2022-10-07 02:25
> I could grab a clip of it if needed.

The more the better :)

**Comment by MythicalBlueFlare** [comment] 2022-10-07 21:31
> 

https://clips.twitch.tv/NimbleArtsyVampireDoggo-C8dURkiydaIw4gLk here you go!

**Comment by LOuroboros** [comment] 2022-10-07 21:34
Grimmsnarl doesn't have a 2nd frame right now, so when the game executes the front sprite animation, that happens as a result probably.

Notice how Grimmsnarl lacks an anim_front.png file.

https://github.com/rh-hideout/pokeemerald-expansion/tree/upcoming/graphics/pokemon/grimmsnarl

**Comment by DizzyEggg** [comment] 2023-02-26 20:25
Got fixed in #2639. Duplicate of #2624

**Closed by DizzyEggg** 2023-02-26 20:25 UTC
Labels: category:battle-related, status: confirmed
