### ISSUE TITLE
Lv 1 mon evolved with stone wants to learn all its Lv 1 moves

### ISSUE THREAD

**Issue by khbsd** [rh-hideout/pokeemerald-expansion#5787] opened 2024-12-08 01:11 UTC
### Description

When evolving a lv 1 mon with a stone, after evolution scene completes, mon will want to learn all of its lv 1 moves after the one(s) it learns on evolving. this does not happen on pret.

![image1](https://github.com/user-attachments/assets/8e9ae3b7-5220-4364-8ae9-ab4d16249a1f)
![image2](https://github.com/user-attachments/assets/e4212f4b-9fdd-4e61-8e7b-9e449d7b8496)
![image3](https://github.com/user-attachments/assets/d009541e-c0f1-48d0-8b3d-e886f54037a1)
![image4](https://github.com/user-attachments/assets/17f70cff-eb73-401a-8f8b-da78eeadd387)
![image5](https://github.com/user-attachments/assets/c3664dcd-95f5-499f-995a-63ac540d6a29)
![image6](https://github.com/user-attachments/assets/cd1b07ec-99ab-4a82-83b3-600e7e721fa5)
![image7](https://github.com/user-attachments/assets/49a492bb-cf66-4cb0-9479-79510256120e)
![image8](https://github.com/user-attachments/assets/516dfaa7-8108-41b6-97ed-82b0702936ef)

tested with level 1 eevee -> glaceon via ice stone and level 1 eevee -> flareon on upcoming, and level 1 eevee -> vaporeon on pret.

### Version

upcoming (Edge)

### Upcoming/master Version

3f3f4cfe1c3d6c156d7570c8a84c390ece1a715f

### Discord contact info

khbsd_

**Comment by hedara90** [comment] 2024-12-08 07:00
At least in Gen 7, this is expected behavior.
Tested on USUM.

**Comment by hedara90** [comment] 2024-12-08 07:12
And in Gen 3, the level 1 learnset for Eevee and its evolutions are identical, so unless the learnsets were edited, they wouldn't learn anything upon evolution.

**Comment by khbsd** [comment] 2024-12-08 07:14
ah, perfect then. should i close?

**Comment by hedara90** [comment] 2024-12-08 07:16
Probably, I can't test gen 8/9.
But as it stands, there is no bug here.

**Comment by AsparagusEduardo** [comment] 2024-12-08 10:00
This does not happen in Gen 9.

**Comment by AsparagusEduardo** [comment] 2024-12-08 10:01
I'll test in Gen 8 in a sec

**Comment by AsparagusEduardo** [comment] 2024-12-08 10:21
And by a sec I mean 2 hours as Im re-downloading the game xD

**Comment by AsparagusEduardo** [comment] 2024-12-08 12:14
Confirmed that it doesn't happen in Gen 8 either

**Comment by hedara90** [comment] 2024-12-08 12:19
Then it's probably a change they did because they added a lot of moves to the level 1 learnset for most mons I checked.

**Comment by Bassoonian** [comment] 2024-12-08 12:32
Config time!

**Comment by hedara90** [comment] 2024-12-09 12:22
Fixed by #5791

**Closed by hedara90** 2024-12-09 12:22 UTC
Labels: bug, status: confirmed
