### ISSUE TITLE
Symbiosis doesn't work in all intended cases

### ISSUE THREAD

**Issue by AgustinGDLV** [rh-hideout/pokeemerald-expansion#4332] opened 2024-04-02 19:30 UTC
### Description

I haven't tested extensively, but a very simple Fling test had Symbiosis not do anything :( will investigate myself and PR a fix since it is my implementation in the expansion.

### Version

upcoming (Edge)

### Discord contact info

agustingdlv

**Comment by DizzyEggg** [comment] 2024-06-17 09:53
Could you share more details about the Fling/Symbiosis interaction? How it should work exactly?

**Comment by hedara90** [comment] 2024-07-25 19:32
I tested fling with Symbiosis right now, and I couldn't see anything wrong with it.

https://github.com/user-attachments/assets/0d6ad98d-189d-4773-aef8-7dd41fe2092c

**Comment by hedara90** [comment] 2024-08-23 10:21
Unless a reproducible example of this still being broken if brought forth, I'd close this since from my testing it seems to work as it's supposed to.

**Comment by hedara90** [comment] 2024-08-31 08:57
Can't replicate, closing.
Reopen with examples if it's still present.

**Closed by hedara90** 2024-08-31 08:57 UTC
Labels: bug, status: needs information, category: battle-mechanic, status: unconfirmed
