### ISSUE TITLE
Magnitude attacking an already dead partner

### ISSUE THREAD

**Issue by cestlarunj** [rh-hideout/pokeemerald-expansion#3514] opened 2023-11-01 16:47 UTC
### Description

![image](https://github.com/rh-hideout/pokeemerald-expansion/assets/63125573/9ad39ac0-240e-41db-9d4c-79def65bd083)

Marshtomp died from one of its opponents, then Donphan used Magnitude, and somehow the move attacked Marshtomp too although he was already dead. The game froze in this state.

### Version

1.6.1

### Discord contact info

cestlarunj

**Comment by AlexOn1ine** [comment] 2023-11-01 19:53
Which move was used to Kill Marshtomp?

**Comment by cestlarunj** [comment] 2023-11-01 19:54
I don't remember the Persian move but Girafarig did Zen Headbutt

**Comment by AlexOn1ine** [comment] 2023-11-01 19:57
> I don't remember the Persian move but Girafarig did Zen Headbutt


Was Zen Headbutt used to KO Marshtomp or was it the other move? 
I suspect it's not a Magnitude issue but of the move that was used to KO Marshtomp. It would be great if you could recreate it and make a video.

**Comment by cestlarunj** [comment] 2023-11-01 20:00
I genuinely don't remember which one was used to kill Marshtomp because I was playing at 4x speed 😬 but i remember Girafarig using Zen Headbutt and I'm pretty sure Persian used Fury Swipes

**Comment by AlexOn1ine** [comment] 2023-11-01 20:16
> I genuinely don't remember which one was used to kill Marshtomp because I was playing at 4x speed 😬 but i remember Girafarig using Zen Headbutt and I'm pretty sure Persian used Fury Swipes

Wasn't able to reproduce it. Maybe someone else has more luck.

**Comment by DizzyEggg** [comment] 2023-11-01 20:20
Are you sure the game froze after Magnitude was used? Moves like Magnitude specifically check that the target is alive, I would be surprised if it somehow failed to check that.

**Comment by cestlarunj** [comment] 2023-11-01 22:32
Yeah i'm pretty sure it was after Magnitude was used. It tried to damage my partner before damaging the foes, and froze on the "critical hit" message. Maybe it has something to do with the crit ?

**Comment by AlexOn1ine** [comment] 2023-11-01 22:44
> Yeah i'm pretty sure it was after Magnitude was used. It tried to damage my partner before damaging the foes, and froze on the "critical hit" message. Maybe it has something to do with the crit ?

The weird thing to me is that the healthbox for Marshtomp is still on the field. My guess is Magnitude sees it as a valid target and tries to do damage calcs after the hit but since it's already dead, the game freezes.

**Comment by Bassoonian** [comment] 2024-01-09 11:23
Closing since it doesn't seem to be reproduceable. Feel free to reopen if you can find a clear way to do so on 1.7.1+.

**Closed by Bassoonian** 2024-01-09 11:23 UTC
Labels: bug, category: battle-mechanic, status: unconfirmed
